pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git clone git@bitbucket.org:duckduckgo95/oop-concepts.git
          - cd oop-concepts.git
          - git push --mirror git@github.com:ijaaz9/oop-concepts.git